### PR TITLE
fix gradient plugin for static prefixer

### PR DESCRIPTION
**Pull request by MrRaindrop**
I've used the static prefixer for my project, and It works greate for most time right now, since my project is only running on mobile platforms. However the transformed result for gradient is not working, because the old vendor style is not quite the same as the standard writing.

So I found the plugin for gradient is just to add vendor prefixes to the given gradient values. The browser will not accept that, and the showing result is quit opposite for vendors version (See the test cases you'll know what I mean) and the standard version. So I add some converting including the direction change and the angle recalculation, and more test cases too.

### CODE REVIEW

**Comment by rofrischmann** [comment]
Can you also fix that for the dynamic version? I'd like to keep both in sync and won't add different prefixing behavior just to one :P

**Comment by MrRaindrop** [comment]
Sure, I'll have a look into that : )

**Comment by rofrischmann** [comment]
@MrRaindrop Is this something you're still going to help us with? Otherwise I will close the PR

**Comment by necolas** [comment]
Is this something that could be reopened and merged? There are several existing differences been static and dynamic versions of this library. If maintaining both is a burden, have you considered dropping the dynamic approach. It's not clear to me that there are any benefits to using it

**Comment by rofrischmann** [comment]
Do we really need syntax compatibility fixes nowadays? If so Im more than happy to reopen and merge that, but it looks like a huge overhead to me.

**Pull request closed without merging**
