### PR TITLE
splits cursor plugin into two separate plugins for zoom and grab, always adds prefix to grab and grabbing

### LINKED ISSUE #79: Incorrect Chrome support for cursor: grab
As far as I can tell, cursor.js is checking for chrome < 37 to decide whether to prefix 'grab' and 'grabbing'. However, even on Chrome 50 I'm seeing the need to still prefix 'grab' and 'grabbing'.

### PR DESCRIPTION
**Pull request by alexyaseen**
This fixes #79

### CODE REVIEW

**Comment by alexyaseen** [comment]
I split the cursor plugin into two plugins as requested (zoom and grab). The grab plugin prefixes grab and grabbing regardless of version reliable info for browser support can be found (per #79)

**Comment by rofrischmann** [comment]
@alexyaseen Thanks a lot, I will merge this as soon as I am ready & at home.

**Comment by alexyaseen** [comment]
@rofrischmann any update on getting this merged in?

**Comment by rofrischmann** [comment]
Yes, I will be merging everything tomorrow and release a new version.

**Pull request merged**
