### PR TITLE
Replace OR with AND operator

### PR DESCRIPTION
**Pull request by tintin1343**
Changed the operators in flexboxIE.js and flexboxOld.js

The issue with the 'OR' operator is that it will create issues in pages which does not have a `display` property. 

Changing the `OR` operator with `AND` will do the work.

Closes https://github.com/rofrischmann/inline-style-prefixer/issues/70

### CODE REVIEW

**Comment by tintin1343** [comment]
@rofrischmann : I do not understand the reason for the tests failure. Could you guide me ?

**Comment by rofrischmann** [comment]
@tintin1343 Heyhey, just check out the issue again :) I ve posted something about it.
To validate my fix you could add this to the tests:

**Current tests**
```javascript
describe('Prefixing display', () => {
  it('should not remove display property', () => {
    expect(new Prefixer({ userAgent: MSIE10 }).prefix({
      display: 'block'
    })).to.eql({ display: 'block' })
  })
})
```

**New tests**
```javascript
describe('Prefixing display', () => {
  it('should not remove display property', () => {
    expect(new Prefixer({ userAgent: MSIE10 }).prefix({
      display: 'block'
    })).to.eql({ display: 'block' })
  })
  it('should not throw if display is null or undefined', () => {
    expect(new Prefixer({ userAgent: Chrome45 }).prefix({
      display: null
    })).to.eql({ display: null })
    expect(new Prefixer({ userAgent: Chrome45 }).prefix({
      display: undefined
    })).to.eql({ display: undefined })
  })
})
```

**Comment by tintin1343** [comment]
@rofrischmann : Ok. I saw your comment on the issue. Let me make the necessary changes and edit my pull request.

**Comment by rofrischmann** [comment]
Alright thanks a lot! Tests seem to pass now :P The only reason for the failed status is actually an issue with codeclimate which I am not sure how to fix right now.

**Comment by tintin1343** [comment]
@rofrischmann : Cool. I was wondering why that was happening when my npm test passed. You are welcome.

**Comment by necolas** [comment]
Does the prefix-all package also need part of this patch?

**Comment by rofrischmann** [comment]
@necolas Actually it should work for your usecase as far as I know you do not have `null` or `undefined` values right? Still I will add this right away.

**Comment by rofrischmann** [comment]
@necolas https://github.com/rofrischmann/inline-style-prefix-all/releases/tag/1.0.2 here we go. I actually could remove this display check at all as we already use the full flex plugin :P

**Pull request merged**
