### PR TITLE
Added support for combined vendor prefixing

### PR DESCRIPTION
**Pull request by Cavitt**
Passing `*` to the Prefixer constructor as the userAgent will combine
prefixes for all vendors. If no user agent is specified and not exposed
in the environment, we default to this mode.

Useful for universal / isomorphic apps as we don't always know the user agent before rendering on the server.
This option is good incase you wish to cache server generated pages and distribute to all browsers,
you can be assured the markup will be the same as the client rendered version.
The drawback is there's no support for vendor alternatives (eg: ie flexbox)

### CODE REVIEW

**Comment by rofrischmann** [comment]
Hey @Cavitt, 
First I'd like to say thanks for contributing!

I am sorry to not be able to check those commits till now, but I'll check those asap tomorrow.
I like the idea to support all prefixes for caching purpose, but what exactly would you do if someone uses IE 10? They'd spot a rendering disaster if the page was built entirely with flexbox :/

**Comment by ianobermiller** [comment]
While it is possible to support all the plugins like flexbox , It would be a non-trivial amount of work to add it to this project as well. There are other projects that use autoprefixer fully to support everything, including all browser differences, on inline styles. https://github.com/UXtemple/babel-plugin-react-autoprefix is one of them, although it does require preprocessing. I wonder if that would be a better fit?

**Comment by Cavitt** [comment]
@rofrischmann yes flexbox is completely broken when using this method, this is just the first iteration. More plugins (including flexbox) can be supported in the future, but as Ian said it's non-trivial.

@ianobermiller hey Ian, been a long time, haha. I wanted to keep using this tool for on-demand client/server prefixing. I can use useragent for that, but eventually having the option to cache or default to a universal stylesheet that most browsers should support (incase we don't recognize a useragent) would be nice.

**Comment by rofrischmann** [comment]
@Cavitt What do you think about spliting the functionality into 2 different methods? This would withdraw complexity and add modularity as it seems to be quite different looking at that code briefly. Don't like that it adds 2 different algorithm within every module. Could be something like `prefix(userAgent)` and `prefixAll`. 

Also we could add a force parameter to every plugin to make sure it always resolves the plugin. My key prio was simplicity :P

**Comment by Cavitt** [comment]
@rofrischmann I agree, it needs to be split up. I'll update my PR soon with the change soon.

**Comment by ianobermiller** [comment]
@Cavitt I was wondering if you were the same person! You don't have any contact info in your GitHub profile.

**Comment by rofrischmann** [comment]
@Cavitt Great! I am looking forward to merge this one.

**Comment by rofrischmann** [comment]
Hey @Cavitt, 
How are you doing with this one :P? I'd love to have that merged into master :>

**Comment by oliviertassinari** [comment]
Me too, It would resolve https://github.com/callemall/material-ui/issues/2119.

**Comment by Cavitt** [comment]
@rofrischmann @oliviertassinari been putting it off since I didn't think anyone was depending on it. I'll have it ready in just a bit.

**Comment by Cavitt** [comment]
Should be good to merge now. `Prefixer.prefixAll(styles)` (see unit test)

**Comment by rofrischmann** [comment]
Dang, thanks for the fast response!

I'll try to merge that later today. Been busy right now :P

**Comment by rofrischmann** [comment]
Hmm, seems like I fucked up the whole git merging step. Was exactly following the command line instructions, but ended up pushing the changes on my own instead of using yours... I'm sorry for that, but at least the changes are released now

**Comment by rofrischmann** [comment]
I am sorry to not be able to replicate the issue, but seems like I am not the best git shaman out there. I'll later list you as a contributor to thank you for pushing this one!

**Pull request closed without merging**
