### PR TITLE
[ES6] Remove the need for the Symbol polyfill

### PR DESCRIPTION
**Pull request by oliviertassinari**
Fix https://github.com/rofrischmann/inline-style-prefixer/issues/58 and should fix my test here https://github.com/FormidableLabs/radium/pull/552.

@rofrischmann Feedback welcomed.

### CODE REVIEW

**Comment by oliviertassinari** [comment]
I'm not sure to understand why the test fails. `No CODECLIMATE_REPO_TOKEN found`?

**Comment by rofrischmann** [comment]
Huh, that should not be an issue. Well, I can see that there's everything fine. Thanks for your help :)

**Comment by oliviertassinari** [comment]
@rofrischmann Thanks! I wasn't sure you where going to merge it :grin:. That's debatable.
I'm wondering why the `npm run test` works on this project and not on the radium one.
I can't find any babel-polyfill installed here. Could this be because of babelv5 (here) / babelv6 (radium)?

**Comment by rofrischmann** [comment]
True. I'd normally not merge something that breaks the tests, but in this case it is just the code quality tool that fails, perhaps because I've set up the repo, but that'd be ridiculous. 

I am not sure if Babel 5 (stage 0) covered the polyfill as well, but could the reason. I know that using `babel-node` automatically uses the polyfill. Perhaps `--compilers js:babel/register` as a mocha argument uses these too.

**Comment by ianobermiller** [comment]
FWIW I definitely prefer `Object.keys` and avoiding `for` loops whenever possible :)

**Pull request merged**
