### PR TITLE
#40 - userAgent of Cordova IOS 8.x lacks version

### PR DESCRIPTION
**Pull request by alexdrel**
Workaround for #40

### CODE REVIEW

**Comment by rofrischmann** [comment]
Shouldn't we further check if it is iOS at all and then set to 8.0 instead of just omitting 0, because that causes every property to get prefixed. Also could you add a //dirty workarround <link-to-this-issue> comment? I'm sure this will soon get fixed in bowser :P

**Comment by alexdrel** [comment]
I doubt it will be ever fixed knowing Apple/Cordova for a while, it is old although still supported version after all.
I beware hardcoding version 8 as I don't have IOS 7 and earlier devices so I'm not sure what is the reported there, so may be it better to be safe. 
Besides putting 8 there will be really //dirty, now it is quite a legitimate fix - bowser may and does not return the version in certain cases - so inline-prefixer handles that cases. If anything dirty 8 should be added in bowser, they already have //WTF comment.

**Comment by rofrischmann** [comment]
Well yeah the WebView userAgents may be quite a mess, but knowing them makes bowser capable of fixing that. Even if they don't do it right now it should be added some day. Still inline-style-prefixer was and is not responsible for detection correctness (as mentioned in the repository) and therefore should not do that in general. That's why I want to have a some kind of comment flag there.

**But actually the main problem is setting to 0**. This will break a lot of stuff e.g. if you prefix `display: flex` you will get `display: -webkit-box` which is not supported. This would even make it worse than just leave the prefixes at all (which iOS is quite good at lately)

**Comment by alexdrel** [comment]
You are right regarding new IOS (9+), but fortunately it does not have this version problem at all - it is sent and detected normally. As of ```display: -webkit-box``` it is supported on IOS 8 - this is one of two bugs that I had needed fixed and it was fixed.
Do you agree that ```NaN``` as a version is much worse than ```0``` as it breaks prefixing completely?

And because I fully accept your reasons:
>Still inline-style-prefixer was and is not responsible for detection correctness (as mentioned in the repository) and therefore should not do that in general. 

I wary to put an ```8```. 

But of course it is your call.

**Comment by rofrischmann** [comment]
It really supports -webkit-box? That really surprises me. So if it fixes everything we can do that. Thanks for mentioning. I suggest adding something to the docs later, after that I'll merge it!

**Pull request merged**
